// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-business-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_business_info_default = defineTool({
  name: "get_business_info",
  title: "Get business info",
  description: "Returns core business information for Lavander\xEDa Fuengirola (OpenBlue): address, opening hours, phone, WhatsApp, email and social profiles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Lavander\xEDa Fuengirola \u2014 OpenBlue",
      tagline: "Lavander\xEDa industrial y autoservicio en Fuengirola. Especialistas en alquiler vacacional (Airbnb).",
      address: "Av. de Mijas n\xBA5, Local 2, 29640 Fuengirola, M\xE1laga, Espa\xF1a",
      hours: "07:00 \u2013 23:00, 365 d\xEDas al a\xF1o",
      phone: "+34 641 819 577",
      whatsapp: "https://wa.me/34641819577",
      email: "info@lavanderiafuengirola.com",
      website: "https://lavanderiafuengirola.com",
      maps: "https://maps.app.goo.gl/bu8z2BPR11gnGxpe6",
      social: {
        instagram: "https://www.instagram.com/openblue_fuengirola/",
        facebook: "https://www.facebook.com/profile.php?id=61575797150377"
      },
      coverage: [
        "Fuengirola",
        "Los Boliches",
        "Torreblanca",
        "Carvajal",
        "Mijas Costa",
        "Benalm\xE1dena Costa",
        "Calahonda",
        "Elviria",
        "Marbella"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "Returns the catalogue of services offered: self-service laundry, vacation-rental logistics (Airbnb), residential, and B2B (property managers, cleaning agencies).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = [
      {
        id: "self_service",
        name: "Autoservicio 24h asistido",
        summary: "Lavadoras y secadoras Girbau industriales de 8-18 kg. Horario 07:00-23:00, todos los d\xEDas."
      },
      {
        id: "vacation_rental",
        name: "Alquiler vacacional / Airbnb",
        summary: "Recogida post check-out, desinfecci\xF3n con ox\xEDgeno activo, custodia gratuita de ropa limpia y entrega Just-in-Time coordinada con el equipo de limpieza."
      },
      {
        id: "residential",
        name: "Particulares",
        summary: "Colada por kilos, lavado + secado + doblado, tintorer\xEDa y prendas delicadas."
      },
      {
        id: "b2b",
        name: "B2B / Property Managers",
        summary: "Contratos a medida para agencias de alquiler vacacional, apartamentos tur\xEDsticos y empresas de limpieza. Facturaci\xF3n mensual y tarifas por volumen."
      },
      {
        id: "cleaning_360",
        name: "Holiday Cleaning 360\xB0",
        summary: "Pack completo: limpieza profesional de la vivienda + lavander\xEDa de textiles, coordinado en un solo proveedor."
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/list-coverage-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_coverage_areas_default = defineTool3({
  name: "list_coverage_areas",
  title: "List coverage areas",
  description: "Returns the geographic areas where OpenBlue offers pickup and delivery on the Costa del Sol.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const areas = [
      { name: "Fuengirola", type: "core" },
      { name: "Los Boliches", type: "core" },
      { name: "Torreblanca", type: "core" },
      { name: "Carvajal", type: "core" },
      { name: "Mijas Costa", type: "core" },
      { name: "Benalm\xE1dena Costa", type: "extended" },
      { name: "Calahonda", type: "extended" },
      { name: "Elviria", type: "extended" },
      { name: "Marbella", type: "extended" }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(areas, null, 2) }],
      structuredContent: { areas }
    };
  }
});

// src/lib/mcp/tools/submit-b2b-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var FORMSPREE_URL = "https://formspree.io/f/xnjbndyz";
var submit_b2b_lead_default = defineTool4({
  name: "submit_b2b_lead",
  title: "Submit B2B quote request",
  description: "Submits a B2B quote request (property managers, cleaning agencies, vacation-rental owners) to OpenBlue. The team responds within 24h.",
  inputSchema: {
    name: z.string().describe("Contact person's full name."),
    company: z.string().describe("Company or property-management brand."),
    email: z.string().describe("Contact email address."),
    phone: z.string().describe("Contact phone number, ideally in international format."),
    service: z.enum(["laundry", "cleaning", "full"]).describe("Service of interest: laundry only, cleaning only, or full pack."),
    zone: z.string().describe(
      "Operational area (e.g. Fuengirola, Los Boliches, Mijas Costa, Benalm\xE1dena, Calahonda, Elviria, Marbella)."
    ),
    weekly_turnovers: z.enum(["1-5", "5-15", "15+"]).describe("Estimated weekly property turnovers."),
    notes: z.string().optional().describe("Optional additional details.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input) => {
    const payload = {
      tipo: "B2B Quote Request (MCP)",
      nombre: input.name,
      empresa: input.company,
      email: input.email,
      telefono: input.phone,
      servicio: input.service,
      zona: input.zone,
      turnovers: input.weekly_turnovers,
      notas: input.notes ?? "",
      origen: "MCP"
    };
    try {
      const res = await fetch(FORMSPREE_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify(payload)
      });
      if (!res.ok) {
        return {
          content: [
            {
              type: "text",
              text: `Lead submission failed with status ${res.status}. Please try again later or contact +34 641 819 577.`
            }
          ],
          isError: true
        };
      }
      return {
        content: [
          {
            type: "text",
            text: "Lead received. The OpenBlue B2B team will reply within 24h."
          }
        ],
        structuredContent: { ok: true }
      };
    } catch (err) {
      return {
        content: [
          {
            type: "text",
            text: `Network error submitting lead: ${err.message}`
          }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lavanderia-fuengirola-mcp",
  title: "Lavander\xEDa Fuengirola (OpenBlue) MCP",
  version: "0.1.0",
  instructions: "Tools for OpenBlue \u2014 Lavander\xEDa Fuengirola. Use `get_business_info`, `list_services` and `list_coverage_areas` to answer questions about the business, hours, contact, services and coverage on the Costa del Sol. Use `submit_b2b_lead` to send a B2B quote request for property managers, cleaning agencies or vacation-rental owners.",
  tools: [get_business_info_default, list_services_default, list_coverage_areas_default, submit_b2b_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
